services:
  github-backup:
    image: github-backup
    build: .
    restart: on-failure:10
    environment:
      - GITHUB_BACKUP_TOKEN=$GITHUB_BACKUP_TOKEN
      - GITHUB_BACKUP_SCHEDULE=$GITHUB_BACKUP_SCHEDULE
      - GITHUB_BACKUP_DIRECTORY=/backup
    volumes:
      - type: bind
        source: $GITHUB_BACKUP_DIRECTORY
        target: /backup